[package]
name = "dual-n-back"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10", features = ["wayland"]}
bevy-inspector-egui = "0.18"

[profile.dev.package."*"]
opt-level = 3

